### ISSUE TITLE
Remove WriteExternalStorage permission.

### ISSUE THREAD

**Issue by ncruces** [KSemenenko/GoogleAnalyticsForXamarinForms#10]
Awesome library. Very useful to do analytics on a PCL.

On Android why are you requesting `WriteExternalStorage` permission ([AssemblyInfo.cs](/KSemenenko/GoogleAnalyticsForXamarinForms/blob/master/Plugin.GoogleAnalytics/Plugin.GoogleAnalytics.Android/Properties/AssemblyInfo.cs#L8))?

You don't need to read/write from `SpecialFolder.Personal`, if that's all you're doing (it seems so, from [DeviceInfo.cs](https://github.com/KSemenenko/GoogleAnalyticsForXamarinForms/blob/master/Plugin.GoogleAnalytics/Plugin.GoogleAnalytics.Android/DeviceInfo.cs#L21)).

Very successful libraries such as [Akavache](https://github.com/akavache/Akavache) get by without such permission, though they use `SpecialFolder.ApplicationData` instead.

I've ran your test app with the permission removed and it works.

**Comment by KSemenenko** [comment]
Thanks for you comment, I'll check it.

**Comment by KSemenenko** [comment]
Please check v. 1.0.1.8 ^_^
Thanks!

**Comment by ncruces** [comment]
Working fine, as expected.
Thanks!
