### ISSUE TITLE
Exceptions contain no stacktrace or source

### ISSUE THREAD

**Issue by nologinatgit** [KSemenenko/GoogleAnalyticsForXamarinForms#11]
I use this library and I could send exceptions to my GA account.

However, when I check the chart, I get only the application name and an empty Stacktrace and Source label.

I use this code:

```
    GoogleAnalytics.Current.Config.TrackingId = "MY_ID";
    GoogleAnalytics.Current.Config.AppId = "com.example.AnalyticsTestGoogle";
    GoogleAnalytics.Current.Config.AppName = "AnalyticsTestGoogle";
    //GoogleAnalytics.Current.Config.Debug = true;
    GoogleAnalytics.Current.InitTracker();
    GoogleAnalytics.Current.Tracker.SendView("MainPage");
    GoogleAnalytics.Current.Tracker.SendException(new Exception("Google Analytics teszt"), false);
```

I get this as a result:

[Exceptions](https://s22.postimg.org/lu2d4p0q9/ga_exceptions.png)

What should I do to have the stacktrace included?

**Comment by KSemenenko** [comment]
Hi, I will check it

**Comment by nologinatgit** [comment]
I tried your suggestion, it look better now, though I still only get one line of stacktrace withiout line numbers and proper stack.
`
Google Analytics teszt; StackTrace: at AnalyticsTestGoogle.App.<>c.<.ctor>b__0_0(Object x, EventArgs y); Source: AnalyticsTestGoogle;`

Can I add even more detail to it?

Also, another question: calling `SendException` is a network operation so it takes time and should be used on another thread.

Can I use `async-await` with it somehow?

**Comment by KSemenenko** [comment]
InnerException is a good idea! I recently add something for this. Also if you have any ideas I think I can implement them)

**Comment by nologinatgit** [comment]
I'll try InnerExceptions as well.
What about the asynchronity? Can you modify to make it `async-await` compatible?

**Comment by KSemenenko** [comment]
are you talking about the Send method?

**Comment by nologinatgit** [comment]
Yes,
I would like to send the data asynchronously.

If you can modify the source to mark the `SendException` method (actually, all the SendXXX methods) as `async` (and also make the send in a separate thread), I could call it with the `await` keyword.

Here is a good tutorial for that: https://codewala.net/2015/08/17/asynchronous-programming-with-async-and-await-explained/

If you change that then the main thread shouldn't have to wait for the network send. Will you consider this?

**Comment by KSemenenko** [comment]
It works this way, http query runs asynchronously. In addition, your code does not need to wait until it is executed.

**Comment by nologinatgit** [comment]
When I call `SendException`, the execution blocks the main thread. Obviously I could create a thread and call the method there, but using `async-await` is a better way.

I measured it exactly, and this lines of code are executed in _822 ms_:
  ```
   try
      {
        stopWatch.Start();
        GoogleAnalytics.Current.Tracker.SendView("MainPage");
        GoogleAnalytics.Current.Tracker.SendEvent("EventCategory1", "Error1");
        string s = null;
        string a = s.Substring(2);
      }
      catch (Exception ex)
      {
        GoogleAnalytics.Current.Tracker.SendException(ex, false);
        stopWatch.Stop();
        (sender as Button).Text = stopWatch.ElapsedMilliseconds.ToString();
      }
```
If the Send methods were async, it should be done about 10 ms. As they block the caller thread, it is nearly 1 s. That is why I suggested to create an async implementation inside the library, using _Tasks_.

**Comment by KSemenenko** [comment]
Start
GoogleAnalytics: Track.
SendView: 00:00:00.0090254
GoogleAnalytics: Track.
SendException: 00:00:00.0254147
GoogleAnalytics: Track.
SendException and Inner: 00:00:00.0060952
GoogleAnalytics: Track.
GoogleAnalytics: Track.
Exception thrown: 'System.NullReferenceException' in TestFormsApp.WinPhone.exe
GoogleAnalytics: Track.
SendException from catch: 00:00:00.3393463
Payload sent! Response:GIF89aPayload sent! Response:GIF89aPayload sent! Response:GIF89aPayload sent! Response:GIF89aPayload sent! Response:GIF89aPayload sent! Response:GIF89aThe thread 0x710 has exited with code 0 (0x0).

**Comment by KSemenenko** [comment]
Looks like all ok, request is performed asynchronously and does not block thread

**Comment by KSemenenko** [comment]
Have you tried the new version? @nologinatgit

**Comment by nologinatgit** [comment]
Not yet, I'll check it tomorrow and report back.

**Comment by nologinatgit** [comment]
I checked it, it still blocks the main thread, in the UWP project it took 2400 ms!

You can check my project [here](https://drive.google.com/open?id=0BzxlsFasHX6uREFrNHRVN05ORmc).

I hope you can find the issue.

**Comment by KSemenenko** [comment]
ok, I will check your project.

**Comment by KSemenenko** [comment]
Hi @nologinatgit I ran your project
And changed only the output time on it in line 99
``` cs
(sender as Button).Text = stopWatch.Elapsed.ToString();
```

so, I get time like
00:00:00.0013948
00:00:00.0033712
