### ISSUE TITLE
Windows-based devices send 0.0.0.0 as program version

### ISSUE THREAD

**Issue by nologinatgit** [KSemenenko/GoogleAnalyticsForXamarinForms#12]
I modified the _Assembly.cs_ in my UWP project, and also the _Package Manifest_ settings with different versions, but in Google Analytics they arrive as 0.0.0.0. 

I tried to overwrite it using this code but didn't work:

```
public string Version
    {
      get
      {
        var version = new Version(Package.Current.Id.Version.Major,
            Package.Current.Id.Version.Minor,
            Package.Current.Id.Version.Revision,
            Package.Current.Id.Version.Build);
        return version.ToString();
      }
    }


GoogleAnalytics.Current.Config.AppVersion = Version;
```

[Version codes](http://s13.postimg.org/l0ebvk1bb/ga_versions.png)

Do you have any idea why?

**Comment by nologinatgit** [comment]
A workaround is if I overwrite the following:

`GoogleAnalytics.Current.Tracker.AppVersion = Version;`

The original problem still persists: why is the version number incorrect inside the library?

**Comment by KSemenenko** [comment]
I used the same code Package.Current.Id.Version

**Comment by KSemenenko** [comment]
This is the PCL project? @nologinatgit
