### ISSUE TITLE
Advertising Id & IDFA

### ISSUE THREAD

**Issue by jderrough** [KSemenenko/GoogleAnalyticsForXamarinForms#13]
Hi,

Is there a way to track demographics using Advertising Id on Android and IDFA on iOS?

Best,
Jonathan

**Comment by KSemenenko** [comment]
Hi, @jderrough 
I don't know work with demographic data.

**Comment by jderrough** [comment]
Hi @KSemenenko ,

After investigating a bit, found out that IDFA and ADID are not documented to be used with Measurement Protocol... Too bad, went with the native components and an abstraction for PCL use.

Thanks anyway :)
