### ISSUE TITLE
Initialisation Crashing on UWP apps

### ISSUE THREAD

**Issue by Yogeshk25** [KSemenenko/GoogleAnalyticsForXamarinForms#15]
I am getting TypeInitializationException on this line

GoogleAnalytics.Current.Config.TrackingId = "UA-XXXXXXXX-X";

But code works fine on Android.
Done these initializations in App.xaml.cs

Is there any special configuration to get it working on UWP?

**Comment by KSemenenko** [comment]
Hi, try update uwp platfroms nuget packages for your UWP project.

**Comment by kiler4747** [comment]
Hello KSemenenko, I have same problem, all nuget packages are updated. Can I use this plugin in clear uwp project without forms?

**Comment by KSemenenko** [comment]
I will check it

**Comment by JeroenBer** [comment]
I have the same problem as well for Universal Windows with updated nuget packages. Any news on this ?

**Comment by KSemenenko** [comment]
@JeroenBer Hi, please check new version!

**Comment by JeroenBer** [comment]
Hi, I further investigated this crash problem on UWP.

It seems to crash on with:
Exception from HRESULT: 0x80070490 
In the DeviceInfo constructor on:
var bounds = ApplicationView.GetForCurrentView().VisibleBounds;

It seems that you are not allowed to call this method too early in the startupproces of your application, see http://stackoverflow.com/questions/27204707/why-is-this-element-not-found.

So initialisation of this library cannot be done to early in the startup proces of you app, or at least the windows has to exist.

**Comment by KSemenenko** [comment]
Hello! Thanks, i will fix it.

**Comment by JeroenBer** [comment]
Thanks

**Comment by KSemenenko** [comment]
Hi. This method is obsolete. And I did not manage to check his work.
