### ISSUE TITLE
Initialisation Crash on WinRT(win8)

### ISSUE THREAD

**Issue by b099l3** [KSemenenko/GoogleAnalyticsForXamarinForms#16]
Exception thrown  when running this code (using my own trackingID not 1111..):
            `GoogleAnalytics.Current.Config.TrackingId = "UA-11111111-1";`

> The type initializer for 'Plugin.GoogleAnalytics.GoogleAnalyticsImplementation' threw an exception. 
> at Plugin.GoogleAnalytics.GoogleAnalyticsImplementation..ctor()
>    at Plugin.GoogleAnalytics.GoogleAnalytics.CreatePluginGoogleAnalytics()
>    at System.Lazy'1.CreateValue()
>    at System.Lazy'1.LazyInitValue()
>    at System.Lazy'1.get_Value()
>    at Plugin.GoogleAnalytics.GoogleAnalytics.get_Current()

Inner exception:

> RunSynchronously may not be called on a task not bound to a delegate, such as the task returned from an asynchronous method.
> at System.Threading.Tasks.Task.InternalRunSynchronously(TaskScheduler scheduler, Boolean waitForCompletion)
>    at Plugin.GoogleAnalytics.DeviceInfo.WriteFile(String path, String content)
>    at Plugin.GoogleAnalytics.PlatformInfoProvider.GetAnonymousClientId()
>    at Plugin.GoogleAnalytics.PlatformInfoProvider..ctor(IDeviceInfo deviceInfo)
>    at Plugin.GoogleAnalytics.PlatformInfoProvider..ctor()
>    at Plugin.GoogleAnalytics.GoogleAnalyticsImplementation..cctor()

May be related to #15

**Comment by KSemenenko** [comment]
Hi, is UWP?

**Comment by b099l3** [comment]
Hi, it is win8 it comes under.

**Comment by KSemenenko** [comment]
ok, it will check it. I had a similar problem due nuget package.

**Comment by b099l3** [comment]
Cool, if there is anything I can help with just let me know.

**Comment by KSemenenko** [comment]
@b099l3 Hi, please check new version
