### ISSUE TITLE
No sessions on analytics.google.com dashboard

### ISSUE THREAD

**Issue by LeifS** [KSemenenko/GoogleAnalyticsForXamarinForms#24]
Hey ksemenenko,
Thanks for making this great plugin for xamarin.
I am experiencing a weird issue, I can see users in real-time, but no session data is ever recorded!

My code initializing your plugin is as follows:

```c
void InitGoogleAnalytics()
{
	GoogleAnalytics.Current.Config.TrackingId = "UA-SECRET_ID-1";
	GoogleAnalytics.Current.Config.AppId      = "com.secret.package";
	GoogleAnalytics.Current.Config.AppName    = "Secret";
	GoogleAnalytics.Current.Config.AppVersion = "0.32";
	//GoogleAnalytics.Current.Config.Debug = true;
	//For tracking install and starts app, you can change default event properties:
	GoogleAnalytics.Current.Config.ServiceCategoryName = "App";
	GoogleAnalytics.Current.Config.InstallMessage = "Install";
	GoogleAnalytics.Current.Config.StartMessage = "Start";
	GoogleAnalytics.Current.Config.AppInstallerId = Guid.NewGuid().ToString();
	GoogleAnalytics.Current.InitTracker();
	//Track view
	//GoogleAnalytics.Current.Tracker.SendView("MainPage");
	GoogleAnalytics.Current.Tracker.UserId = Guid.NewGuid().ToString();
	GoogleAnalytics.Current.Tracker.SetStartSession(true);
}
```

I send views for each page I want tracked, and I also send events for user actions I want tracked.
It all shows up in the real-time display, but none of it is recorded past that as session data.

Please let me know if I'm messing something up.

Leif

**Comment by KSemenenko** [comment]
Hello @LeifS !

Config looks redundant.
Try it like this:

```
GoogleAnalytics.Current.Config.TrackingId = "UA-SECRET_ID-1";
GoogleAnalytics.Current.Config.AppId = "com.secret.package";
GoogleAnalytics.Current.Config.AppName = "Secret";
GoogleAnalytics.Current.Config.AppVersion = "0.32";
GoogleAnalytics.Current.InitTracker();
```
and track view like this:
```
GoogleAnalytics.Current.Tracker.SendView("MainPage");
```

_GoogleAnalytics.Current.Tracker.SetStartSession (true);_ - does not start a new session, only sending the event starts the session.

By the way 
```
GoogleAnalytics.Current.Config.AppInstallerId = Guid.NewGuid (). ToString ();
```
Every new startup will be like a new installation.

About real time. In Google analytics it works strange. Not all events fall into a real-time report.
And not always in real time.
In order to make sure that this works you can make a statistic request.

**Comment by LeifS** [comment]
@KSemenenko 
Thanks for getting back to me.
I cleaned up my config code and made it as you suggested.

The real-time data shows up perfectly fine, but I never see users, sessions, or any historical data.

Pics related: 
[Analytics Dashboard](http://i.imgur.com/orN6qeT.png)
[Event Data](http://i.imgur.com/x46wLGi.png)

**Comment by LeifS** [comment]
@KSemenenko 
Analytics have now started to show up! Thanks for the help.
