### ISSUE TITLE
Uncaught exceptions are being reported

### ISSUE THREAD

**Issue by luccasclezar** [KSemenenko/GoogleAnalyticsForXamarinForms#29]
As the title says, all uncaught exceptions are being reported even when I add `GoogleAnalytics.Current.Config.ReportUncaughtExceptions = false`.

I tried to look the cause of this, and I found this file: https://github.com/KSemenenko/GoogleAnalyticsForXamarinForms/blob/master/Plugin.GoogleAnalytics/Plugin.GoogleAnalytics.Android/GoogleAnalyticsPlatform.cs

It always adds an exception handler, not taking into consideration the ReportUncaughtExceptions property. 

Is it possible to have a workaround to not send exceptions?

**Comment by KSemenenko** [comment]
Hello! As you can see, it doesn't have implemented. But you can help to fix it.

**Comment by luccasclezar** [comment]
Is that it? :)
