### ISSUE TITLE
Always sending data twice after 1.0.3.1

### ISSUE THREAD

**Issue by luccasclezar** [KSemenenko/GoogleAnalyticsForXamarinForms#31]
After the last update, all data is getting saved twice.

![captura de tela 6](https://user-images.githubusercontent.com/12024080/35751223-dca11b0e-083e-11e8-8f90-6ce18c2fe9d9.png)

This screen capture is showing a test session that I did, and it's pretty clear that it's duplicating everything. And I'm sure it's only in this version as I tested with 1.0.3 and it's working as expected.

Any ideas where this issue might be coming from?

**Comment by luccasclezar** [comment]
Please, this is a major issue with this library, some people might be using it without even noticing the duplicated data.

**Comment by KSemenenko** [comment]
@luccasclezar Hello, I'l check it

**Comment by KSemenenko** [comment]
@luccasclezar please try v.1.0.3.2

**Comment by luccasclezar** [comment]
@KSemenenko It's fixed, thank you!
