### ISSUE TITLE
Cannot add Nuget to PCL project

### ISSUE THREAD

**Issue by labretrox** [KSemenenko/GoogleAnalyticsForXamarinForms#5]
Hallo,

VS 2015 Professional Update 2. Here is an output:

Attempting to gather dependency information for package 'ksemenenko.GoogleAnalytics.1.0.0.1' with respect to project 'Gifts', targeting '.NETPortable,Version=v4.5,Profile=Profile111'
Attempting to resolve dependencies for package 'ksemenenko.GoogleAnalytics.1.0.0.1' with DependencyBehavior 'Lowest'
Resolving actions to install package 'ksemenenko.GoogleAnalytics.1.0.0.1'
Resolved actions to install package 'ksemenenko.GoogleAnalytics.1.0.0.1'
Attempting to gather dependency information for package 'ksemenenko.GoogleAnalytics.1.0.0.1' with respect to project 'Gifts.WinPhone', targeting 'WindowsPhoneApp,Version=v8.1'
Attempting to resolve dependencies for package 'ksemenenko.GoogleAnalytics.1.0.0.1' with DependencyBehavior 'Lowest'
Resolving actions to install package 'ksemenenko.GoogleAnalytics.1.0.0.1'
Resolved actions to install package 'ksemenenko.GoogleAnalytics.1.0.0.1'
Attempting to gather dependency information for package 'ksemenenko.GoogleAnalytics.1.0.0.1' with respect to project 'Gifts.iOS', targeting 'Xamarin.iOS,Version=v1.0'
Attempting to resolve dependencies for package 'ksemenenko.GoogleAnalytics.1.0.0.1' with DependencyBehavior 'Lowest'
Resolving actions to install package 'ksemenenko.GoogleAnalytics.1.0.0.1'
Resolved actions to install package 'ksemenenko.GoogleAnalytics.1.0.0.1'
Attempting to gather dependency information for package 'ksemenenko.GoogleAnalytics.1.0.0.1' with respect to project 'Gifts.Droid', targeting 'MonoAndroid,Version=v6.0'
Attempting to resolve dependencies for package 'ksemenenko.GoogleAnalytics.1.0.0.1' with DependencyBehavior 'Lowest'
Resolving actions to install package 'ksemenenko.GoogleAnalytics.1.0.0.1'
Resolved actions to install package 'ksemenenko.GoogleAnalytics.1.0.0.1'
Install failed. Rolling back...
Package 'ksemenenko.GoogleAnalytics.1.0.0.1' does not exist in project 'Gifts'
Package 'ksemenenko.GoogleAnalytics.1.0.0.1' does not exist in folder 'C:\Projects\CrossPlatform\ceneo.xamarin.gifts\packages'
Could not install package 'ksemenenko.GoogleAnalytics 1.0.0.1'. You are trying to install this package into a project that targets '.NETPortable,Version=v4.5,Profile=Profile111', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.
========== Finished ==========

**Comment by KSemenenko** [comment]
HI, thanks for the info, I will fix it

**Comment by labretrox** [comment]
Thank you for the update. There is another compatybility problem, could you have a look please?

Attempting to gather dependency information for package 'ksemenenko.GoogleAnalytics.1.0.0.4' with respect to project 'Gifts', targeting '.NETPortable,Version=v4.5,Profile=Profile111'
Attempting to resolve dependencies for package 'ksemenenko.GoogleAnalytics.1.0.0.4' with DependencyBehavior 'Lowest'
Resolving actions to install package 'ksemenenko.GoogleAnalytics.1.0.0.4'
Resolved actions to install package 'ksemenenko.GoogleAnalytics.1.0.0.4'
Attempting to gather dependency information for package 'ksemenenko.GoogleAnalytics.1.0.0.4' with respect to project 'Gifts.WinPhone', targeting 'WindowsPhoneApp,Version=v8.1'
Attempting to resolve dependencies for package 'ksemenenko.GoogleAnalytics.1.0.0.4' with DependencyBehavior 'Lowest'
Resolving actions to install package 'ksemenenko.GoogleAnalytics.1.0.0.4'
Resolved actions to install package 'ksemenenko.GoogleAnalytics.1.0.0.4'
Attempting to gather dependency information for package 'ksemenenko.GoogleAnalytics.1.0.0.4' with respect to project 'Gifts.iOS', targeting 'Xamarin.iOS,Version=v1.0'
Attempting to resolve dependencies for package 'ksemenenko.GoogleAnalytics.1.0.0.4' with DependencyBehavior 'Lowest'
Resolving actions to install package 'ksemenenko.GoogleAnalytics.1.0.0.4'
Resolved actions to install package 'ksemenenko.GoogleAnalytics.1.0.0.4'
Attempting to gather dependency information for package 'ksemenenko.GoogleAnalytics.1.0.0.4' with respect to project 'Gifts.Droid', targeting 'MonoAndroid,Version=v6.0'
Attempting to resolve dependencies for package 'ksemenenko.GoogleAnalytics.1.0.0.4' with DependencyBehavior 'Lowest'
Resolving actions to install package 'ksemenenko.GoogleAnalytics.1.0.0.4'
Resolved actions to install package 'ksemenenko.GoogleAnalytics.1.0.0.4'
Package 'Microsoft.Bcl.Build.1.0.14' already exists in folder 'C:\Projects\CrossPlatform\ceneo.xamarin.gifts\packages'
Added package 'Microsoft.Bcl.Build.1.0.14' to 'packages.config'
Executing script file 'C:\Projects\CrossPlatform\ceneo.xamarin.gifts\packages\Microsoft.Bcl.Build.1.0.14\tools\Install.ps1'...
You cannot call a method on a null-valued expression.
At C:\Projects\CrossPlatform\ceneo.xamarin.gifts\packages\HockeySDK.WINRT.4.1.1-build17552\tools\init.ps1:3 char:1
+ $project.DTE.ItemOperations.Navigate('https://github.com/bitstadium/H ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : InvokeMethodOnNull
 
Successfully installed 'Microsoft.Bcl.Build 1.0.14' to Gifts
Package 'Microsoft.Bcl.1.1.10' already exists in folder 'C:\Projects\CrossPlatform\ceneo.xamarin.gifts\packages'
Added package 'Microsoft.Bcl.1.1.10' to 'packages.config'
Successfully installed 'Microsoft.Bcl 1.1.10' to Gifts
Package 'Microsoft.Net.Http.2.2.29' already exists in folder 'C:\Projects\CrossPlatform\ceneo.xamarin.gifts\packages'
Added package 'Microsoft.Net.Http.2.2.29' to 'packages.config'
Successfully installed 'Microsoft.Net.Http 2.2.29' to Gifts
  GET https://api.nuget.org/packages/ksemenenko.googleanalytics.1.0.0.4.nupkg
  OK https://api.nuget.org/packages/ksemenenko.googleanalytics.1.0.0.4.nupkg 715ms
Installing ksemenenko.GoogleAnalytics 1.0.0.4.
Adding package 'ksemenenko.GoogleAnalytics.1.0.0.4' to folder 'C:\Projects\CrossPlatform\ceneo.xamarin.gifts\packages'
Added package 'ksemenenko.GoogleAnalytics.1.0.0.4' to folder 'C:\Projects\CrossPlatform\ceneo.xamarin.gifts\packages'
Added package 'ksemenenko.GoogleAnalytics.1.0.0.4' to 'packages.config'
Successfully installed 'ksemenenko.GoogleAnalytics 1.0.0.4' to Gifts
Package 'ksemenenko.GoogleAnalytics.1.0.0.4' already exists in folder 'C:\Projects\CrossPlatform\ceneo.xamarin.gifts\packages'
Added package 'ksemenenko.GoogleAnalytics.1.0.0.4' to 'packages.config'
Successfully installed 'ksemenenko.GoogleAnalytics 1.0.0.4' to Gifts.WinPhone
Install failed. Rolling back...
Package 'Microsoft.Bcl.Build.1.0.14' does not exist in project 'Gifts.iOS'
Could not install package 'Microsoft.Bcl.Build 1.0.14'. You are trying to install this package into a project that targets 'Xamarin.iOS,Version=v1.0', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.
========== Finished ==========

**Comment by KSemenenko** [comment]
I have an error in determining the nuget targetFramework. I hope to finish today

**Comment by KSemenenko** [comment]
Seems as though I fix it in version 1.0.0.11
@labretrox  can you check it?

**Comment by labretrox** [comment]
Yep, I'm able to add packages to solution. Great job! Thank you.

**Comment by KSemenenko** [comment]
Thank you, please note that all values are portable library screen and UserAgent string sizes must be entered by hand.
I work on it))
