### ISSUE TITLE
Additional issue adding nuget to Xamarin PCL Project

### ISSUE THREAD

**Issue by ryanspiffy** [KSemenenko/GoogleAnalyticsForXamarinForms#7]
I am attempting to install this package in a project that is targeting PCL Profile 259.  The following is the error I am receiving from Xamarin Studio.

Could not install package 'ksemenenko.GoogleAnalytics 1.0.0.19'. You are trying to install this package into a project that targets 'portable-net45+win+wpa81+wp80+MonoTouch10+MonoAndroid10+xamarinmac20+xamarintvos10+xamarinwatchos10+xamarinios10', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.

**Comment by KSemenenko** [comment]
Hi, please check 1.0.0.20 version from NuGet
