### ISSUE TITLE
Question: Google Analytics Plugin

### ISSUE THREAD

**Issue by dakamojo** [KSemenenko/GoogleAnalyticsForXamarinForms#8]
With the Google Analytics Plugin, is it necessary to track at least one page or event in order for the session to get recorded?  I'm porting a native app to Xamarin.Forms.  We use Google Analytics, but do not track page view or events.  We only track sessions.  I'm using your plugin but not doing anything after InitTracker.  I'm not seeing any sessions logged in GA.

**Comment by KSemenenko** [comment]
I'll try to do something, it's a good issue! @dakamojo

**Comment by dakamojo** [comment]
Thanks.  In the interim I guess we can log one event named "App Start" or something.

**Comment by KSemenenko** [comment]
[GA Docs](https://developers.google.com/analytics/devguides/collection/analyticsjs/field-reference#session)

**Comment by KSemenenko** [comment]
Hi @dakamojo please check version 1.0.2.1.
