### ISSUE TITLE
Question:  Example of initializing tracker with correct IPlatformInfoProvider?

### ISSUE THREAD

**Issue by dakamojo** [KSemenenko/GoogleAnalyticsForXamarinForms#9]
Do you have an example of how to initialize a tracker with the correct IPlatformInfoProvider for the specific platform?

**Comment by dakamojo** [comment]
To clarify.  My goal is to track the device manufacturer, device model, operating system, and operating system version.  Looking through the code it doesn't appear that these attributes are tracked.  Is that correct?

**Comment by KSemenenko** [comment]
Hi, you can see [IPlatformInfoProvider.cs](https://github.com/KSemenenko/GoogleAnalyticsForXamarinForms/blob/master/Plugin.GoogleAnalytics/Plugin.GoogleAnalytics.Abstractions/IPlatformInfoProvider.cs)

```
var trackerManager = new TrackerManager(new PlatformInfoProvider()
{
    ScreenResolution = new Dimensions(1920, 1080),
    UserAgent = "Mozilla/5.0 (Windows NT 6.3; WOW64; Trident/7.0; rv:11.0) like Gecko",
    UserLanguage = "en-us",
    ViewPortResolution = new Dimensions(1920, 1080)
});
``` 
**ScreenResolution** and **ViewPortResolution** contains screen resolution.
**UserAgent** contains specific user agent who get GA info about your device.
**UserLanguage** is user language
